Update compile_docs.yml

diff --git a/.github/workflows/compile_docs.yml b/.github/workflows/compile_docs.yml
--- a/.github/workflows/compile_docs.yml
+++ b/.github/workflows/compile_docs.yml
@@ -69,6 +69,24 @@ jobs:
           ls -l docs/out_html
           echo "::set-output name=VERSION_NAME::$(scripts/find_version.sh)"
         id: version
+          # Publish built docs to gh-pages branch.
+      # ===============================
+      - name: Commit documentation changes
+        run: |
+          #git clone https://${{secrets.GITEE_USERNAME}}:${{secrets.GITEE_PASSWD}}@gitee.com/${{secrets.GITEE_USERNAME}}/test.git --branch master --single-branch master
+          #https://e.coding.net/weidongshan/sphinx_docs/100ask_project_docs.git
+          git clone https://${{secrets.CODING_USERNAME}}:${{secrets.CODING_PASSWD}}@e.coding.net/weidongshan/sphinx_docs/test.git --branch master --single-branch master
+          cp -r out_html/* master/ && cp docs/LVGL.pdf master/
+          cd master
+          touch .nojekyll
+          git config --local user.email "baiwenwang@100ask.com"
+          git config --local user.name "www.100ask.org"
+          git add .
+          git commit -m "Update documentation" -a || true
+          git push origin master
+          # The above command will fail if no changes were present, so we ignore
+          # that.B_TOKEN }}
+    # ===============================
       #- name: Deploy
       #  uses: JamesIves/github-pages-deploy-action@3.7.1
       #  with:
